echo "Archive:"
echo "" 
echo "tar cf file.tar files – создать tar-архив с именем file.tar содержащий files"
echo "tar xf file.tar – распаковать file.tar"
echo "tar czf file.tar.gz files – создать архив tar с сжатием Gzip"
echo "tar xzf file.tar.gz – распаковать tar с Gzip"
echo "tar cjf file.tar.bz2 – создать архив tar с сжатием Bzip2"
echo "tar xjf file.tar.bz2 – распаковать tar с Bzip2"
echo "gzip file – сжать file и переименовать в file.gz"
echo "gzip -d file.gz – разжать file.gz в file"
