echo "Files and base commands:"
echo ""
echo "ls – список файлов и каталогов"
echo "ls -al – форматированный список со скрытыми каталогами и файлами"
echo "cd dir – сменить директорию на dir"
echo "cd – сменить на домашний каталог"
echo "pwd – показать текущий каталог"
echo "mkdir dir – создать каталог dir"
echo "rm -rf file – удалить file или папку"
echo "rm -r dir – удалить каталог dir"
echo "rm -r -f /path – удалить каталог dir"
echo "rm -f file – удалить форсированно file"
echo "rm -rf dir – удалить форсированно каталог dir"
echo "cp file1 file2 – скопировать file1 в file2"
echo "cp -r dir1 dir2 – скопировать dir1 в dir2; создаст каталог dir2, если он не существует"
echo "mv file1 file2 – переименовать или переместить file1 в file2. если file2 существующий каталог — переместить file1 в каталог file2"
echo "ln -s file link – создать символическую ссылку link к файлу file"
echo "touch file – создать file"
echo "cat > file – направить стандартный ввод в file"
echo "more file – вывести содержимое file"
echo "head file – вывести первые 10 строк file"
echo "tail file – вывести последние 10 строк file"
echo "tail -f file – вывести содержимое file по мере роста, начинает с последних 10 строк"
