echo "System Information"
echo "" 
echo "date – вывести текущую дату и время"
echo "cal – вывести календарь на текущий месяц"
echo "uptime – показать текущий аптайм"
echo "whoami – имя, под которым вы залогинены"
echo "uname -a – показать информацию о ядре"
echo "cat /proc/cpuinfo – информация ЦПУ"
echo "cat /proc/meminfo – информация о памяти"
echo "man command – показать мануал для command"
echo "df – показать инф. о использовании дисков"
echo "du – вывести “вес” текущего каталога"
echo "free – использование памяти и swap"
echo "whereis app – возможное расположение программы app"
echo "which app – какая app будет запущена по умолчанию"
